const levels: Record<string, { label: string; description: string }> = {
  level_0: {
    label: "Level 0 — No meaningful AI evidence detected",
    description: "Analysis did not find significant evidence of AI generation or AI-assisted modification.",
  },
  level_1: {
    label: "Level 1 — AI-assisted",
    description: "Minor AI-assisted elements may be present, such as enhancement or noise reduction.",
  },
  level_2: {
    label: "Level 2 — AI-enhanced",
    description: "The content shows signs of meaningful AI enhancement or modification of original media.",
  },
  level_3: {
    label: "Level 3 — AI-generated component",
    description: "The content appears to contain a significant AI-generated component, while other portions may originate from real media.",
  },
  level_4: {
    label: "Level 4 — Heavily synthetic",
    description: "Most of the analyzed content appears to be AI-generated or heavily modified by AI systems.",
  },
  level_5: {
    label: "Level 5 — Predominantly synthetic",
    description: "The content appears to be predominantly or entirely generated by AI systems.",
  },
};

export default function ClassificationLevel({ level }: { level: string }) {
  const cfg = levels[level] || levels.level_0;
  const idx = parseInt(level.replace("level_", ""), 10) || 0;

  return (
    <div className="rounded-xl border border-slate-200 p-6 bg-white">
      <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-4">AI Classification</h3>
      <div className="flex items-center gap-3 mb-3">
        <div className="flex gap-1">
          {[0, 1, 2, 3, 4, 5].map((i) => (
            <div
              key={i}
              className={`w-6 h-2 rounded-full ${
                i <= idx
                  ? idx <= 1
                    ? "bg-emerald-400"
                    : idx <= 3
                      ? "bg-yellow-400"
                      : "bg-red-400"
                  : "bg-slate-200"
              }`}
            />
          ))}
        </div>
      </div>
      <p className="font-semibold text-slate-800 mb-1">{cfg.label}</p>
      <p className="text-sm text-slate-500">{cfg.description}</p>
    </div>
  );
}
