import { Microscope } from "lucide-react";

export default function LocalAnalysisBanner() {
  return (
    <div className="bg-sky-50 border border-sky-200 rounded-lg px-4 py-3 flex items-start gap-2 text-sm text-sky-800">
      <Microscope className="w-4 h-4 mt-0.5 shrink-0" />
      <span>
        This report was generated by TrustLens&apos; built-in{" "}
        <strong>local heuristic engine</strong> — it analyzes the file&apos;s real
        metadata and statistical features (deterministic: the same file always
        gives the same result). For deep-learning grade AI/deepfake detection,
        connect a neural provider (Hive or Sightengine).
      </span>
    </div>
  );
}
